name: CI Pull Request Action
on:
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    name: Build simple project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Test project
        run: npm test
        id: test
      - name: Check test status
        if: ${{ steps.test.outcome != 'success' }}
        run: |
          echo "::set-output name=test-status::failure"